---
type_regex: !!map
  deposit: "(^TransferDeposit.*)|(^TransferGoGrowMainRepaiment.*)"
  withdraw: "(^Withdraw.*)|(^TransferGoGrow$)"
  interest: "(^TransferInterestRepaiment.*)|(^TransferExtraInterestRepaiment.*)"
  fee: "(^FX commission.*)"

csv_fieldnames:
  booking_date: 'TransferDate'
  booking_date_format: '%d.%m.%Y %H:%M'
  booking_details: 'Description'
  booking_id: 'LoanNumber'
  booking_type: 'Description'
  booking_value: 'Amount'
  booking_currency: 'Currency'
